### ISSUE TITLE
Small spelling mistake - mangnitude

### ISSUE THREAD

**Issue by andrewbaxter439** [asjadnaqvi/DiD#10]
As I note, small typo:

https://github.com/asjadnaqvi/DiD/blob/ad00723c02fe6f894a28f84e7dd6b2f28f1ece83/docs/code/06_bacon.md?plain=1#L518

(if helpful to note typos etc. I'm happy to fork repo and do larger read-through at some point - a very helpful guide!)

**Comment by asjadnaqvi** [comment]
Thanks for finding this! I have fixed it. A read through will be great but the pages are currently being reorganized for the next updates
