### ISSUE TITLE
fuzzydid command

### ISSUE THREAD

**Issue by OscarAndresMartinez** [asjadnaqvi/DiD#13]
Dear professor 
Thanks for your DID repository, I have two questions related fuzzydid stata command and G variable, Could you explain the step by step about fuzzydid that in your repository?

I have a panel data set with a continuous treatment at level country-year that change over time and it´s set one for each unit, I read the did_multiplegt for estimating treatment effect, I have a problem to create G variable, my treatment is anually by country as ID and my period of time is from 2000 to 2014
Could you explain me how do you create this G variable please?     

Thanks for your comments   
All the best

**Comment by asjadnaqvi** [comment]
Dear Oscar,

I did not write the fuzzydid package and know very little about it. In any case the authors have newer packages like `did_multiplegt`  (https://asjadnaqvi.github.io/DiD/docs/code/06_did_multiplegt/) that is much more advanced that `fuzzydid`. I would highly recommend using one of the newer packages. You can see how the variables are constructed in the link above.
