### ISSUE TITLE
stackedev error

### ISSUE THREAD

**Issue by emily-frank** [asjadnaqvi/DiD#23]
Hi! Feels like a simple question, but I'm looking at the full code provided on https://asjadnaqvi.github.io/DiD/ and I'm getting an error with the command `stackedev Y F_* L_* ref, cohort(first_treat) time(t) never_treat(never_treat) unit_fe(id) clust_unit(id)` because `ref` has not been defined. I can't find anywhere else in the code where it's defined... does anyone know what it should be defined as? 

Thank you!

**Comment by asjadnaqvi** [comment]
will check!

**Comment by asjadnaqvi** [comment]
The reference base year has to be defined as follows:

```stata
ren F_1 ref  //base year
```

and then run the command:

```
stackedev Y F_* L_* ref, cohort(first_treat) time(t) never_treat(no_treat) unit_fe(id) clust_unit(id)
```
