### ISSUE TITLE
Packages w links

### ISSUE THREAD

**Issue by cseveren** [asjadnaqvi/DiD#4]
Thanks for the aggregator on new DD stuff. Here are a couple papers and links to add:

- Tymon Słoczyński, “Interpreting OLS Estimands When Treatment Effects Are Heterogeneous: Smaller Groups Get Larger Weights,” forthcoming in *Review of Economics and Statistics*, link (R and Stata packages available): https://people.brandeis.edu/~tslocz/software.html, plus recent Twitter discussion: https://twitter.com/agoodmanbacon/status/1455262252441948164
- A cluster of papers with R software by Imai and Kim, all linked to here: https://imai.fas.harvard.edu/research/FEmatch.html

**Comment by asjadnaqvi** [comment]
Thanks! Will add these next update.

**Comment by asjadnaqvi** [comment]
Added!
