### ISSUE TITLE
Manual recovery of weights in Bacon Decomposition

### ISSUE THREAD

**Issue by wenddymacro** [asjadnaqvi/DiD#5]
there is a error in folloeing code:

display "weight_le = " (((ne + nl) * (De))^2 * nel * (1 - nel) * (Dl / De) * ((De - Dl)/(De)) ) / VD

it would be 

display "weight_le = " (((ne + nl) * (De))^2 * nel * (1 - nel) * (Dl / De) * ((De - Dl)/(1-De)) ) / VD

**Comment by asjadnaqvi** [comment]
Thanks @wenddymacro for picking this up! This Stata formula is correct but its latex code shown above it wrong, which I have now corrected. I double checked with the paper here as well: https://www.sciencedirect.com/science/article/pii/S0304407621001445
