### ISSUE TITLE
R code

### ISSUE THREAD

**Issue by grantmcdermott** [asjadnaqvi/DiD#8]
Hi Asjad,

Thanks for putting together this excellent public good. 

Would you be open to adding R code examples that match the existing Stata pages on the site? 

I know most of the packages quite well and should be able to get a PR submitted fairly quickly if you're up for it.

The main structural thing we'd have to think about ahead of time is organization of the repo for navigation. E.g. Would you want (tabbed?) R and Stata code on the same page, or should they just resolve to separate subdirs?

**Comment by asjadnaqvi** [comment]
Dear Grant,

That would be awesome! Have been looking for someone to complete the R part for a while.

I would prefer a separate R directory and subfolders. This will ensure that the R section itself reads smoothly. One can always cross-reference if needed.

**Comment by asjadnaqvi** [comment]
1) Yep that is fine! As long as the relative paths are fixed and the pages don't break.

2) That is fine. Let's standardize id and time to `id` and `time`. I will change it once you push the updates. I also have a couple of minor errors to fix so I will do it in one go.

3) Yep. I have been planning to do this for a while now. The initial thinking was to keep each page complete especially if someone is interested in just one estimator. But it makes more sense to have a dedicated data generation page.
